---
services:
  python:
    build:
      context: python/
      dockerfile: Dockerfile
      args:
        - UID
        - GID
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ../:/workspaces
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: demo
      TZ: Asia/Tokyo
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
volumes:
  mysql_data:
